<template>
  <div class="pageLayoutBg pa-3"> 
    <div class="d-flex justify-center">
      <div class="d-flex align-center" style="flex-flow:column wrap">
        <img src="/logo.png" style="max-width:250px"/>
        <div class="text-center">
          <h1>LASKAR MAHAKARYA 2023</h1>
        </div>
      </div>
    </div>
    <div class="d-flex justify-center text-center">
      SELAMAT BAGI PARA PEMENANG!
    </div>
    <div class="d-flex justify-center text-center mt-3" >
        <div>
          <v-text-field v-model="search" solo-inverted prepend-inner-icon="mdi-magnify" placeholder="Cari Pemenang" > </v-text-field>
      </div>
    </div>
    <div class="d-flex justify-center">
      <div style="max-width:500px">
        <v-data-table :search="search" :headers="headers" :items="items"></v-data-table>
      </div>
    </div>
  </div>
</template>

<style>
.pageLayoutBg {
  background:url('/bg.jpg');
  background-size: cover;
  min-height: 100vh;
}
</style>

<script>
import Logo from '~/components/Logo.vue'
import VuetifyLogo from '~/components/VuetifyLogo.vue'

export default {
  components: {
    Logo,
    VuetifyLogo
  },
  data(){
    return {
      headers: [{
        text:'Nama Pemenang', value:'name'
      }],
      search:'',
      items:[],
      winners:["GHOFUR", "SALSA", "TOKO JITUN", "IPAH BENDA", "H DALMADI", "ASYIK GERABAH", "KRIS", "IZZAN", "ALAN", "DIKOH", "LUMAYAN", "TOKO AVI JAYA", "RIAS CELL", "SUUDI", "MARYATI", "WINARSIH", "IJAH", "RONI", "ASMINI", "LUNA PUTRA", "SANTOSA", "MAKDUM", "SAFI'I", "TOKO ASLAM", "SAAL", "ASWATI", "TK. PUTRA PANDAWA", "JUJU", "SUKUR", "CIPTADI", "SRI", "ENDANG", "IYUNG", "ERLIN", "EDY", "MURNI", "SUCI", "MASITOH", "WARTIAH", "MINOLTA", "TOKO HESTI", "NURYATI", "UMI", "UUS", "SRI", "ENY", "NASUKHA", "TANUJI", "TK. ALADIN", "NUR", "SUKADI", "ZAKY", "IBU SUMINI", "FATONAH", "YAYAH", "SENTOT", "ABC", "JULI", "NUR KHALIMAH", "NASIATUN", "LASMI", "KANTIN GEMBIRA", "TOKO EDIANTO", "ATUN", "FURQON", "DARSO", "KUSGIARNI", "SAYIDAH", "SAADAH", "KASTANI", "IRFAN", "WAHYUDI", "RIFKI", "SAMIAN", "PARJIANI", "IIN", "SITOH", "SUKIRMAN", "IDA", "SINAR TERANG", "H. MASKURI", "RAHMAT/IING", "TOKO BOGA", "NABILA", "MUADAH", "BERKAH ILLAHI", "FASIHAH", "SOMARI", "MASITOH", "DWIYATI", "IHYAK", "BERKAH AKHLIS", "TIBIN", "TARJONO", "TK KRIS", "MAMIK", "WAHITI", "SUTARNI", "YAYAN", "SAMSUDIN", "TK. SASA", "TOKO RISKY", "TOKO BOWO", "TOKO WARSONO", "TOKO HERMANTO", "KURNIA", "MADRUN", "ANYAR", "PARIKHIN", "CAHAYA PUTIH", "URIPAH", "MUSLIKHAH", "TK KOSIM", "TOKO AFIFAH", "KHANAPI", "NOVA", "ANI", "NISA", "SUBUR", "TK YATI", "YANTI", "EDY", "TK. FATIMAH", "MUSLIH", "TK. ALI", "TOKO JM CELL", "EMAH", "TOKO HENDRO", "TOKO TARSINAH", "CHAWADIEST", "SUSWATI", "INAH", "MBAK CUS", "MAS AGUS", "HJ. SUKATI", "AQILA", "TK. SAMIAJI", "SOFI", "DIAZ", "TK.HELMI", "HJ. MUNASRIFAH", "TK.AWALIYAH", "YATI", "WATI", "TK. NUNUNG", "RIYATNO", "ANTIK (ISI ULANG)", "JORDAN", "ENDANG", "DUA PUTRI", "H. KIBIK", "IBU MURNI", "TK. HIDAYAH", "FADIL", "ROKHIMAH", "RIO", "TK. OVA", "TOFIK", "TK. ELMI", "MURNI", "BILQIS", "DUTA WANGI", "SAIKOU", "TK. FATKHUL", "SORIDAH", "TK. SALSA", "DMV CELL", "TK. YAYUK", "TK. ISTIKHAROH", "ARUM", "PUTRA", "RASSYA", "SALAMAH", "TK. WIDYA", "TOKO ALIN", "TK. NAROYAH", "ARIANA", "TOKO BADRIAH", "TOKO PRIMA", "INTAN CELL", "SENO", "TK. AMINAH", "SM", "KASMIAH", "SOLIKHAH", "TK OSI", "BASIR", "TK. RAMSAH", "FATIMAH", "OYAH", "TK ANIS", "KHOPIPAH", "I'IM", "MULYA JAYA", "JATIMULYA CELL", "ALIF JAYA", "TOKO AA", "TOKO KOTILAH", "TOKO NADA", "SULEMAN", "EDI WIJAYA", "DNA CELL", "NUNUNG", "TK HARMONY", "TOKO YUSUF PUTRA", "EXTRA CELL", "TOKO IJO", "PAK TO", "TOKO INA", "TOKO RAHMA", "TOKO MBA OOM", "TK NURHAYATI", "TOKO NAJWA", "BU NENENG", "KOMARIYAH", "BASO OMBER", "SUNU", "NANDA CELL", "TK. HARYONO", "TK HERI", "TK. INTAN", "IKHSAN MOTOR", "TOKO NISA", "ZIDNI CELL", "TK. MARINA", "TK. KHOLIFAH", "ANGGUN CELL", "IMAS", "LINDA", "ARI", "ALFIN CELL", "BU EMI", "WM URIYAH", "TK. MUZAKHIM", "TOKO SUMBER BERKAH", "JAM'AN", "TOKO AFIQ", "TK. TAUFIK", "IBU NUR", "TK. ANISA", "TK. MIRNA", "TK AZKA", "TK ICIH", "HJ. IIN", "TK. NAJLI", "MBA SUSI", "FITRO", "MAHFIROH", "TK. SRI REJEKI", "FARHAN", "TK. NADIA", "SRI MURTININGSIH", "TOKO VICKY", "SUIROH", "TK WARYO", "TK. 21", "TK. WIRYO", "MBA SUSI", "DIAZ CELL", "IROH", "TOKO ASIF", "NELI MUNAYAH", "TK MULYO", "TK. SRI", "TIARA", "RUHANAH", "TK NOVAL", "TANTI", "ANIS", "LUBIS JAYA", "H. IDA", "NAYU", "TK TABUN", "WINDA CELL", "WR. NARSIEM", "TK. BU SULASTRI", "TK. H. SAADAH", "H. EDI", "USWATUN", "HARTI BAYU", "TOKO NUR IKHSAN", "MAFRIKHATI", "SERUROH", "SAEFUL", "TK. BERKAH MULYA", "TK. SANITI", "TK. IWAN", "TK. YANTI", "TOKO CAHAYA", "TK TOYO", "FINIA CELL", "TK IPAH", "ALVIN JAYA", "TK. FITRI", "DUA PUTRA", "TK MBA NUR", "FATIH CELL", "IRMAWATI", "SUKIRNO", "TK. ULI FITRIANI", "ALDY CELL", "NAFISAH", "TK. FITRI", "TK DARSONO", "IBNU CELL", "SUKHEMI", "ZAKY", "TK MBA YANI", "TK. 39 JAYA", "TOKO SALAMAH", "TK. BAGAS", "RAHAYU", "RIZKY AZIS", "TOTO", "TK. RESTU CELL", "TK. IBU ERI", "TK SEKAR JAYA", "WILLY CELL", "TK. NUNUNG", "JAMILAH", "TOKO DEDE", "PUTRI TUNGGAL", "TK SARDINAH", "TOKO UMI", "MAMA RIKY", "TK. FAUZAN", "LEKHA", "TOKO SIM. C", "TOKO IA", "MUGI LARIS", "TK. NAUFAL", "M. CARI", "TOKO MBA MANUT", "IZZA CELL", "TK. EKO", "TK SUMBER REJEKI", "TK. ZAENAL ARIFIN", "TK. HIDAYAH", "TK. TUTIK", "TK. SHOLATUN", "TOKO SANOVA", "H. DAMSIRI", "RUMI", "TOKO NABIL", "TOKO BAROKAH", "TK. SERBA", "TK AMEL", "TK. BAIKHAQI", "TK HUSEN", "ROSYATI", "H. MUNIR", "TK. IDJAH", "TOKO KRISTAL", "BU ROHAH", "TK. DUA VITA", "BU YUS", "TOKO YONO", "TK ROYANAH", "WR RIZKY", "U CELL", "TOKO SAMUEL", "TOKO GHINA", "TOKO JIHAN", "BA TOSERBA", "BU RASMEN", "TK. MBA ERNA", "ANTO CELL", "TK ANYAR", "TK INA", "AYU MAREK", "BANG EDI", "TK. RISQI CELL", "TK. KUSRINI", "TK. BU WIWIN", "RAHMA CELL", "JUNI", "ROMYATI", "TOKO KORIAH", "TOKO DOIS", "TOKO ANA", "TK.ASRI", "BU KHOLIDAH", "TK. ENGGANG", "TK. YUYUN", "TOKO BU TIAMAH", "WAKHIDIN", "TK EKA", "TK. RAYA", "MBAK TRIA", "PLANTUR KIOS", "TOKO RINA", "LUTFI", "TK. SUTRIAH", "BLUE CHERRY", "TK. FIRA", "RORO", "ZALFA CELL", "ATIN", "INDAH", "TK. INDAH", "TOKO TOHAR", "TK RAMDI", "ZULFA CELL", "MBA HATIN", "IBU YATI", "WR. OJOLALI", "BINTANG", "UPIT", "KALIMAH", "SUMA CELL", "YENNI", "TOKO MUKIDIN", "FAJRI", "TOKO PUJI", "TK SIROH", "ROHANI", "TOKO LISTYAN", "TOKO TALITA", "TOKO SEMBAKO SUMBER RIZQI", "ZAVA CELL", "TK ASIH", "TOKO SUBUR", "CITRA", "TOKO LAELI", "MUFIYAH", "TOKO SOFIE", "BU WARTIMAH", "MBAK DAH", "NARA SHOP", "TOKO MIKRO", "TOKO ADITYA", "TK. ROSA", "TOKO KAYLA", "TK YAN", "WARUNG ALVA", "TOKO RIZKI", "TOKO PETRA", "TOKO ASHVIENA", "ZEHAN", "TOKO NURYATI", "TK WIWIT", "TK RERE", "PUTRA SADEWA", "IKA", "LIZA", "TARSITI", "TOKO PUTRI", "WATI", "TK. SUKESIH", "TK IFA", "TK. RIYANTI", "TK. ISNA", "WARSO", "ALIN", "MBA ISTI", "TK RIZQI", "RIZQUNA", "TK. NARTI", "TOKO LASTRI", "BU SRI", "TOKO PAK TAUFIK", "\"TOKO \"\"45\"\"\"", "TOKO MBA IS", "MBA ROHMAH", "HASYIM", "TK FATONAH", "TOKO JAYUS", "TUNAS ABDI JAYA", "TK LELI JAYA", "TOKO KUSUMA JAYA", "TOKO SAYO", "ROZANAH", "ILHAM", "TK ARUM", "SUNARYO", "TOKO ESTI", "TK. WAHIDIN", "TOKO YATI JAYA", "FRISKA CELL", "TOKO EDI", "OTOY CELL", "TK. ELA NASWA", "RATMO", "TOKO AYU BINTI SAEFUL", "DUA PUTRA", "TOKO RINI", "AGIS", "TIGA PUTRI", "AYU AULIA", "TOKO KENAN", "POKEMON CELL", "ROJIYAH", "DICKY CELL", "TOKO IBU SUGIARTI", "TOKO MAS ANAM", "TOKO ZAIDAH", "TOKO RODI", "TK RISKIKU", "ZIZI", "NURJANAH", "LOSTA CELL", "RAMA CELL", "BU RODIYAH", "SISKA MIYATI", "TK AZAM", "TOKO NALA", "NADHILA", "TK KHOTIMAH", "UMAR", "KRISTIAWATI", "NAURA", "ENY", "RUSMANTO", "BU ROMDONAH", "ROMBONG ISROMAH", "FJ MAKMUR", "TK DILA", "CASRINAH", "NJ PAPUA", "BRUGRAWUT", "KURYATI", "TK KETAPANG", "TK HARIS", "TK ILMA", "CENI", "KURNIA", "TOKO RADES", "TK GENDHIS LEGI", "TK JIZO", "HERU", "WM AKRAB", "TK MEKAR", "RAHMA", "TK ARRAHMA", "TK RAFIAH", "TK AISYAH", "MUFIDHA", "TK. DENI", "MIKO", "AZZAHRA �CELL", "TOKO YOYO", "TOKO DIKA", "MAMAEH AHLAM", "BU KHOTIJAH", "TOKO UMI", "TOKO WAKIAH", "TOKO DAFA", "TOKO SALSABILA", "NOVI", "TK HJ RATINAH", "TRI", "MBA PAAH", "TOKO FAHMI", "TK.EDY", "TK PIKA", "TK SLAMET", "TK SUMBER TANI", "TK SELO", "BU DARSIH", "TOKO CARKESIH", "TOKO AFNAN", "AYU", "TK SUMBER BARU", "BISMILLAH", "TOKO ANI", "NAURA CELL", "TOKO RUIYAH", "TOKO TIKA", "SOIMAH", "ILHAM CELL", "RIDHO CELL", "HALIMAH", "BAHWAR", "TK. YULI", "TOKO GISEL", "SAMROH", "PUJI CELL", "TK RUDI", "TOKO NAJWA", "TOKO BETI", "TOKO NIZAM", "SEMBAKO FITRI SNACK", "BAIM CELL", "ARSY", "TOKO WAFA FOTO COPY", "SALSABILA", "TK JJS", "TOKO IBU SULIYATI", "TOKO MBA KARIEN", "TOKO GAYA", "FARHAH", "TOKO FADHOL", "TK HASAN", "WR MBA MAP", "TOKO ZAHRA", "TK. SILVINA", "BU SAROH", "MARYAM /ATK 39", "TOKO IMAM", "ERNA", "BU KHOLIFAH", "WRNG MAS MATUL", "BU TUATUN", "BU SANTO", "TOKO ZIDAN", "BABA DZIKRI", "TK ASWA", "PATOK", "TOKO EVAN", "TOKO SAATUN", "TOKO ASYA", "UBAB", "TOKO TANTI", "TK PUTRI", "TK FADLI", "TK AGUNG", "TK NUR/WATIAH", "TK YAYAT", "TK NUR", "TK. NAOMI", "BU MUR", "TOKO POZA", "TOKO YUMI", "ALFA CELL", "ZIDNA", "BU SUNNAH", "TOKO MA SOP", "TK MUSLIMIN", "TK KHARISMA JAYA", "MENTARI", "TOKO BU KUSMENTI", "TK AA MART", "TOKO DEWE/ ZENUDIN", "TK MUBAIDAH", "WR SURYO", "LIA", "TOKO WARSIM", "TRIAH", "WARUNG LATUN", "TK PAK KUSNAN", "WARUNG 77", "BUNDA KAILA", "TK. CANTIKA", "SRI SUhARTi", "KEDAI SP KU", "TOKO INDAH", "YASMIN. CELL", "TOKO LYTA", "WARDEG IBU SUHAEMI", "TOKO HJ KUNAH", "TOKO LULU", "TOKO HAVIZ CELL", "TOKO RISQI", "TK WAIDAH", "TK KHAZIA", "TK. AUFAL", "SAKAREPMU", "TK COOL MART", "TK ELSA 2", "TK CHACHA", "TK ILMI", "TK BIMA", "KANTIN BTN BATARA", "MAMA ARA", "BERKAH PANDAK", "TK SM PUTRI", "Angel Cell", "TK SYAHRUL", "TOKO ABAH ZIO", "MBAK TAMI", "TOKO DAHLAN", "WR BAROKAH", "TOKO ASKA", "TK AAS", "TOKO SIMPANG LIMA", "TK RMS RISKI", "TK RASYA", "TOKO IBU HJ ENNY", "WARUNG BU ATUN", "BAROKAH CIKAL", "TOKO YUYUN", "TOKO NOVAL", "TOKO UYUN", "TOKO ASEP", "MBA SRI", "TOKO DAFFA", "TK AA", "TK NURKHOLIS", "MBAK KUS", "JAJANAN MAMA FATHAN", "TOKO 3R", "TOKO PANCING BLUE FISH", "KM 7", "BU SARMINI", "TK BUDI", "ARFARIZKY", "Toko Family", "\"TK, KUNING\"", "TOKO AA FAHRUL", "AL-AMIN", "KRATON CELL", "TOKO AB BERKAH PUTRA", "AGEN BRI ABDUL ROZAK", "TOKO ANAFI", "TOKO UMAR", "SATRIA CELL", "TAUFIQ", "TK. RIZQUNA", "TOKO KURNIA", "ZIBELLA", "KENANGAN", "TOKO BU DEWI", "TK KURNIA", "WR. PAK. PRIYO", "TK.TRI MAULANA", "Gunung Mas", "PAK ROSIDI", "TK BERKAH MULYA", "SEMI JAYA", "WR SEMBAKO BU JAHRO", "TK. IBU Yanti", "ALEX KANTIN PROYEK", "SHAFA"]
    }
  },
  created(){
    this.winners.forEach((item)=>{
      this.items.push({name:item})
    })
  }
}
</script>
